### ISSUE TITLE
Root repo README should provide install instructions 

### ISSUE THREAD

**Issue by appsforartists** [angular/material-adaptive#4]
By convention, I should be able to skim the root README and know how to run this locally.

**Comment by ThomasBurleson** [comment]
The root of the repository is container for multiple adaptive applications.... each app will have its own readme with its own specific install/run instructions.

> We will be improving this root notes in the near future.

**Comment by ThomasBurleson** [comment]
@see https://github.com/angular/material-adaptive/blob/master/shrine/README.md
